name: "PR to infobloxopen/threat-intelligence"
on:
  workflow_dispatch:
    inputs:
      pull_request_title:
        description: "Pull request name for new PR in infobloxopen/threat-intelligence new PR"
        required: true
      target_branch:
        description: "Branch name for new PR in infobloxopen/threat-intelligence new PR"
        required: true
      commit_message:
        description: "Commmit message to appear in infobloxopen/threat-intelligence new PR"
        required: true

jobs:
  pr-to-threat-intel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo into main
        uses: actions/checkout@v4

      - name: Checkout infobloxopen/threat-intelligence
        uses: actions/checkout@v4
        with:
          # repository: infobloxopen/threat-intelligence
          repository: apowis/pylint-issue
          path: threat-intelligence


      - name: Copies indicators folder to infobloxopen/threat-intelligence
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.PYLINT_WRITE }}
        with:
          source-directory: 'indicators/'
          commit-message: ${{ github.event.inputs.commit_message }}
          destination-github-username: 'infobloxopen'
          destination-repository-name: 'threat-intelligence'
          target-branch: ${{ github.event.inputs.target_branch }}
          target-directory: 'indicators/'
          create-target-branch-if-needed: true
