name: "PR to infobloxopen/threat-intelligence"
on:
  workflow_dispatch:
    inputs:
      pull_request_title:
        description: "Pull request name for new PR in infobloxopen/threat-intelligence new PR"
        required: true
      branch_name:
        description: "Branch name for new PR in infobloxopen/threat-intelligence new PR"
        required: true
      commit_message:
        description: "Commmit message to appear in infobloxopen/threat-intelligence new PR"
        required: true

jobs:
  pr-to-threat-intel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo into main
        uses: actions/checkout@v4

      - name: Checkout infobloxopen/threat-intelligence
        uses: actions/checkout@v4
        with:
          repository: infobloxopen/threat-intelligence
          path: threat-intelligence

      - name: Copy indicators to infobloxopen/threat-intelligence
        run: echo 'yay' > threat-intelligence/temp.txt
      #     ls -l
      #     pwd
      #     ls -l ..
      #     cp -r pywordle/ threat-intelligence/lib/

      - uses: EndBug/add-and-commit@v9
        with:
          message: '${{ github.event.inputs.commit_message }}'
          add: 'temp.txt'
          new_branch: ${{ github.event.inputs.branch_name }}
          cwd: './threat-intelligence/'
          default_author: user_info
          push: true
