name: "PR to infobloxopen/threat-intelligence"
on:
  workflow_dispatch:
    inputs:
      pull_request_title:
        description: "Pull request name for new PR in infobloxopen/threat-intelligence new PR"
        required: true
      branch_name:
        description: "Branch name for new PR in infobloxopen/threat-intelligence new PR"
        required: true
      commit_message:
        description: "Commmit message to appear in infobloxopen/threat-intelligence new PR"
        required: true

jobs:
  pr-to-threat-intel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo into main
        uses: actions/checkout@v4

      - name: Checkout cyberint-databricks
        uses: actions/checkout@v4
        with:
          repository: apowis/pylint-issue
          path: threat-intelligence

      - name: Copy indicators to infobloxopen/threat-intelligence
        run: |
          ls -l
          pwd
          ls -l ..
          cp -r pywordle/ threat-intelligence/lib/

      - name: git add and commit new combined.csv
        run: |
          cd threat-intelligence/
          git switch -c ${{ github.event.inputs.branch_name }}
          git add lib
          git commit -m '${{ github.event.inputs.commit_message }}'
          gh pr create --title "${{ github.event.inputs.commit_message }}" --head "${{ github.event.inputs.branch_name }}" --base main
        #   add: indicators/combined.csv
        #   cwd: './threat-intelligence/'
